### ISSUE TITLE
解析某个网站的时候会陷入或许是死循环

### ISSUE THREAD

**Issue by bahkxiao** [AiursoftWeb/Pylon#1]
`      
var httpService = new HTTPService(null);
var strData =await httpService.Get(new Aiursoft.Pylon.Models.AiurUrl("https://bsaber.com/"),false);
var htmlDoc= HtmlConvert.DeserializeHtml(strData);
`

**Comment by Anduin2017** [comment]
It was not an issue related to `Aiursoft.Pylon`

Please open an issue under HSharp here:

https://github.com/Anduin2017/HSharp
